### ISSUE TITLE
.pem capability

### ISSUE THREAD

**Issue by Madseason41** [ldez/traefik-certs-dumper#1]
Any chance you can add the ability to automatically create the .pem crt/key files?

**Comment by ldez** [comment]
What do you mean by "automatically"?
Could you give a concrete use case?

**Comment by Madseason41** [comment]
Forgive my lack of knowledge, I will do the best i can.
I use a docker traefik image to handle getting the certs for a home website (homeassistant). For certain functions of the website to work, i need to point the program to the .pem files. As far as I know, it doesn't accept .key or .crt file extensions.

https://www.home-assistant.io/docs/ecosystem/certificates/tls_self_signed_certificate/

**Comment by ldez** [comment]
The certificate (`.crt`) and the key (`.key`) are already PEM encoded.
Than it's just a filename extension issue.

**Comment by Madseason41** [comment]
I believe you are right. I guess I just need to change the extension.

https://stackoverflow.com/questions/991758/how-to-get-pem-file-from-key-and-crt-files

**Comment by ldez** [comment]
I will create an option to do that for you :wink:

**Comment by Madseason41** [comment]
> 
> 
> I will create an option to do that for you 😉

Thanks, you are awesome!

**Comment by ldez** [comment]
It's done :tada: (v1.1.0)

```bash
traefik-certs-dumper dump --crt-ext=.pem --key-ext=.pem
```

```yaml
Dump the content of the "acme.json" file from Traefik to certificates.

Usage:
  traefik-certs-dumper dump [flags]

Flags:
      --crt-ext string   The file extension of the generated certificates (default ".crt")
      --dest string      Path to store the dump content. (default "./dump")
  -h, --help             help for dump
      --key-ext string   The file extension of the generated privates keys (default ".key")
      --source string    Path to 'acme.json' file. (default "./acme.json")
```

**Comment by ldez** [comment]
But certificates and keys are still in a different folder. I'm not sure if it's a good idea or not.

**Comment by ldez** [comment]
I added the option (v1.2.0):

```bash
traefik-certs-dumper dump --use-subdir=false --crt-ext=.pem --key-ext=.pem --dest="/home/your_user/.homeassistant/"
```

```yml
Dump the content of the "acme.json" file from Traefik to certificates.

Usage:
  traefik-certs-dumper dump [flags]

Flags:
      --crt-ext string   The file extension of the generated certificates. (default ".crt")
      --dest string      Path to store the dump content. (default "./dump")
  -h, --help             help for dump
      --key-ext string   The file extension of the generated private keys. (default ".key")
      --source string    Path to 'acme.json' file. (default "./acme.json")
      --use-subdir       Use separated directories for certificates and keys. (default true)
```

**Comment by Madseason41** [comment]
> 
> 
> But certificates and keys are still in a different folder. I'm not sure if it's a good idea or not.

You are correct. I tried both updated versions. With renaming the .key and .crt file and placing in same folder I believe one gets overwritten.

In the below link they rename to certificate.pem and privatekey.pem. So probably best to leave in separate folders or add option to rename. I am trying to check and make sure the .pem files work in separate folders. Will let you know soon. Thanks for the quick response.

https://www.home-assistant.io/docs/ecosystem/certificates/tls_self_signed_certificate/

**Comment by ldez** [comment]
I replaced `--use-subdir` by `--domain-subdir`. (v1.3.0)

```bash
traefik-certs-dumper dump --domain-subdir=true --crt-ext=.pem --key-ext=.pem --dest="/home/your_user/.homeassistant/"
```
```yml
Dump the content of the "acme.json" file from Traefik to certificates.

Usage:
  traefik-certs-dumper dump [flags]

Flags:
      --crt-ext string   The file extension of the generated certificates. (default ".crt")
      --dest string      Path to store the dump content. (default "./dump")
      --domain-subdir    Use domain as sub-directory.
  -h, --help             help for dump
      --key-ext string   The file extension of the generated private keys. (default ".key")
      --source string    Path to 'acme.json' file. (default "./acme.json")
```

**Comment by ldez** [comment]
v1.4.0
```console
$ traefik-certs-dumper dump --domain-subdir=true --crt-ext=.pem --key-ext=.pem
dump
├──my.domain.com
│  ├──certificate.pem
│  └──privatekey.pem
└──private
   └──letsencrypt.key
```
