### ISSUE TITLE
Does not extract - Docker - output folders are empty

### ISSUE THREAD

**Issue by user897943** [ldez/traefik-certs-dumper#100]
I'm running it on docker with the following command:

`sudo docker run -v /home/pi/dockers/traefik/:/input -v /home/pi/dockers/traefik/certoutput:/output ldez/traefik-certs-dumper:latest file --source /input/acme.json --dest /output`

what terminal shows me:

```
output
├──certs
└──private

```

I navigate to /home/pi/dockers/traefik/certoutput, I do ls -a, there are two folders: certs, private
I cd into each, do ls -a, they are both empty inside.

I cd back to /home/pi/dockers/traefik and issue sudo rm -R certoutput, then ls -a and I can see it was deleted as wanted.

I issue again:

`sudo docker run -v /home/pi/dockers/traefik/:/input -v /home/pi/dockers/traefik/certoutput:/output ldez/traefik-certs-dumper:latest file --source /input/acme.json --dest /output`

I navigate to /home/pi/dockers/traefik/certoutput which is now created by the container, I do ls -a, there are two folders: certs, private
I cd into each, do ls -a, they are both empty inside, again.

I am PULLING MY HAIR.

Please help. What am I doing wrong?

**Comment by ldez** [comment]
Hello,

on which version of Traefik are you trying to extract certificates?

https://github.com/ldez/traefik-certs-dumper#examples

**Comment by user897943** [comment]
2.2.1

**Comment by user897943** [comment]
I am VERY sorry. There's nothing wrong. I don't know how I could've missed the Note: to dump data from Traefik v2, the CLI flag --version v2 must be added.

Could you maybe make it a little bigger and more prominent? I'd guess most people use traefik v.2 because it's the only version that supports tcp/udp proxying...

It worked with the flag, thank you! Appreciate your work.

**Comment by varac** [comment]
I lost some time on this as well, @ldez please document this behaviour more prominently on the `README.md`.
A verbose flag would be helpful in such case. Also, please consider making using v2 the default since it's the default traefik version for a while now. Thanks !
