### ISSUE TITLE
Support watch for file mode

### ISSUE THREAD

**Issue by andig** [ldez/traefik-certs-dumper#13]
Watch support has been implemented for kv stores as part of https://github.com/ldez/traefik-certs-dumper/pull/10. Would be great to get watch support for file mode, too. This would allow to replace [DanielHuisman/traefik-certificate-extractor](https://github.com/DanielHuisman/traefik-certificate-extractor) with a pure go version.

*Update* I'm gonna give it a try ;)

**Comment by andig** [comment]
@ldez I've found https://github.com/rjeczalik/notify is quite popular for watching files, but I couldn't find out what traefik is using. Might make sense to stick to the traefik standard- could you kindly give a hint?

**Comment by ldez** [comment]
https://github.com/ldez/traefik-certs-dumper/tree/feature/file-watch

**Comment by andig** [comment]
Ohhhhhhh, sorry- seems its already there. Sorry- please close if not relevant.
