### ISSUE TITLE
Add support for other certificate file standards

### ISSUE THREAD

**Issue by alxpettit** [ldez/traefik-certs-dumper#152]
I'm trying to set up an email server with poste.io, using this cert dumper -- but it produces `cert.pem`/`key.pem` as its output format. Poste expects `ca.crt`, `server.crt`, and `server.key`. It would be awesome to add support for outputting these, or at least documentation on a workaround.

**Comment by ldez** [comment]
Hello,

You can already change the filename and extension.
- https://github.com/ldez/traefik-certs-dumper#change-file-extension
- https://github.com/ldez/traefik-certs-dumper#change-file-name

**Comment by alxpettit** [comment]
This doesn't seem to solve the problem:

```
  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:v2.7.4
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /input/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /input/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
      --source /input/acme.json --dest /output/'
      --crt-name=ca.crt --key-name=server.crt
      --domain-subdir=false
    volumes:
      - /stack/${COMPOSE_NAME}/data/ssl/:/output
      - /stack/traefik/data:/input/
 ```
 
 produces separated `certs` & `private` directories, split by domain, and possibly in the wrong format too, given that Poste is expecting the fullchain to be split into the chain and the actual cert, from what I can tell.

**Comment by ldez** [comment]
could you try:
```
--crt-name=server.crt --key-name=server.crt
```
instead of:
```
--crt-name=ca.crt --key-name=server.crt
```

**Comment by alxpettit** [comment]
```
Error: --crt-ext (".crt") and --key-ext (".crt") are identical, in this case --domain-subdir is required
```

**Comment by ldez** [comment]
I don't know Poste could you give me a link to the documentation?

**Comment by alxpettit** [comment]
This has nothing to do with Poste -- it's the output of `traefik-certs-dumper`.

**Comment by ldez** [comment]
Do you have an issue to setup Poste with the current certificates output?
- if yes, I'm interested in the use case, so I want the documentation.
- if no, I need a concrete use case to create a feature, without use-case I will not add a feature.

**Comment by alxpettit** [comment]
Oh, but this issue is still closed? I thought you weren't going to make any changes to the program.

If you're opening it, I'll look into grabbing the readme file from the `ssl` directory, et al. :)

**Comment by ldez** [comment]
Could you point me to the section about certificates? Because the documentation is really sparse.

**Comment by alxpettit** [comment]
Sadly, I don't think there _is_ one. The documentation is bundled in the image itself. It's very strange.
