### ISSUE TITLE
make domain name as crt-name and key-name

### ISSUE THREAD

**Issue by thisisbenwoo** [ldez/traefik-certs-dumper#182]
Hi there, 

This is the perfect solution for what I'm looking for. I'm wondering if I could suggest the opportunity to name the crt and key name files as the domain name, i.e. example.com.crt and example.com.key.

Thanks again for creating this!

ben

**Comment by ldez** [comment]
Hi,

the domain is already used to name files:

https://github.com/ldez/traefik-certs-dumper#examples

**Comment by thisisbenwoo** [comment]
Hmm.. I think I've been trying too many other problems! Thank you for putting up with the question! :-(

**Comment by ldez** [comment]
It's because you are using `--domain-subdir=true`

**Comment by thisisbenwoo** [comment]
@ldez,

I'm sorry, I feel like I'm not expressing what I want clearly. I _do_ want the domain-subdir, but I also want the crt and key files to be named as the domain as well.

So, I want the directory structure as domain1.com, domain2.com, etc.
But I also want the files within the directory tree to be named domain1.com.crt and domain1.key.

One way of representing it might be:
/data/**domain1.com** which has 2 files **domain1.com.crt** and **domain1.com.key**
/data/**domain2.com** which has 2 files **domain2.com.crt** and **domain2.com.key**
etc.

ben

**Comment by zgqq** [comment]
+1  Any news on this?
