### ISSUE TITLE
Add jq during build of the docker image

### ISSUE THREAD

**Issue by DennisGaida** [ldez/traefik-certs-dumper#184]
I don't quite understand why `jq` is added via `apk add jq` in the `entrypoint` in all examples, e.g. here: https://github.com/ldez/traefik-certs-dumper/blob/master/docs/docker-compose-traefik-v2.yml making image startup slow because `jq` is downloaded / installed on each start.

`jq` doesn't add much to the base image, so why not just add it to the Dockerfile https://github.com/ldez/traefik-certs-dumper/blob/master/tmpl.Dockerfile? This way the container could skip all networking `networking: none` for just exporting certs to file.

**Comment by encie22** [comment]
Just in case this is helpful to anyone, I'm working around this by extending the original image.

In a "certs-dumper" folder, create the `Dockerfile`:

```
FROM ldez/traefik-certs-dumper:latest

RUN apk --update upgrade \
    && apk --no-cache --no-progress add jq
```

Then my `docker-compose.yaml` file is as follows:

```
services:
  traefik:
    image: traefik:v3.1
...

  certs-dumper:
#    image: ldez/traefik-certs-dumper:latest
    build: ./certs-dumper
    entrypoint: sh -c '
      while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json | jq -s "add"` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
      --source /data/acme.json --dest /data/certs
      --domain-subdir=true'
...
```

Worth noting that in addition to removing the `apk add` call in the entrypoint, my `jq` line is also adjusted to work with multiple resolvers as discussed [here](https://github.com/ldez/traefik-certs-dumper/issues/134#issuecomment-1575460060).

**Comment by ldez** [comment]
I changed the way to build Docker images and added `jq`

https://github.com/ldez/traefik-certs-dumper/blob/48166b4990cf3d8b31e5c26dd4c37438c735efaf/buildx.Dockerfile#L4
