### ISSUE TITLE
Possible to export a subdomain from a wildcard domain?

### ISSUE THREAD

**Issue by juxeii** [ldez/traefik-certs-dumper#187]
Hi,

is it possible to export a `subdomain `from a wildcard entry in `acme.json`?
For example, can we export `app.domain.com` from `*.domain.com`?

My Synology won't let me import wildcard certificates correclty :(

**Comment by ldez** [comment]
Hello,

a wildcard certificate doesn't contain other certificates.

If you want a certificate for a specific domain you have to create it.

Traefik uses [lego](https://github.com/go-acme/lego) to create certificates automatically based on routers. So you can either change your router configuration or use a standalone version of [lego](https://github.com/go-acme/lego).
