### ISSUE TITLE
change filename of wildcard certificates

### ISSUE THREAD

**Issue by cellerich** [ldez/traefik-certs-dumper#20]
First, thanks for your code!

When I run this on a Windows Filesystem my wildcard certificates and keys will get a cryptic filename since `*.example.com` is not a valid filename.
Would it be possible to change the code or provide a runtime flag to change wildcard filenames into `#.example.com` instead?

**Comment by ldez** [comment]
Thanks for reporting.

I published a new version (v2.2.3), the `*` are automatically replaced by `_` on Windows.

**Comment by cellerich** [comment]
Perfect! Thanks a lot.

**Comment by roquemore92** [comment]
Would it be possible to make this an option even when on Linux machines? I have this running as a docker container on Linux, but I do need to use the certs on other systems, including Windows, and they have trouble with the folder names created from the wildcard certs.
