### ISSUE TITLE
cannot dump certificate with --version v3

### ISSUE THREAD

**Issue by hengeb** [ldez/traefik-certs-dumper#205]
The `traefik-certs-dumper` expects the traefik version with the  `--version` argument. But with the current version v3 the dumper will only create an empty folder `/tmp/work/private`. With `--version v2` the dump is created correctly (even if the actual version is v3).

**Comment by ldez** [comment]
Hello,

Traefik v2 and v3 Traefik has the exact same format, so you can use `--version v2`.

**Comment by ldez** [comment]
I added the value v3 to avoid ambiguity.
