### ISSUE TITLE
private/letsencrypt.pem Purpose

### ISSUE THREAD

**Issue by Aetherinox** [ldez/traefik-certs-dumper#206]
Not an issue, but more of a question.

I have the container set up to use the following:
```
    traefik-certs-dumper:
        container_name: traefik-certs-dumper
        image: ${TRAEFIK_CERTS_IMAGE:-ldez/traefik-certs-dumper}:${TRAEFIK_CERTS_TAG:-v2.8.3}
        restart: unless-stopped
        entrypoint: sh -c '
            apk add jq
            ; while ! [ -e /data/acme.json ]
            || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
            sleep 1
            ; done
            && traefik-certs-dumper file --version v2 --source /data/acme.json --dest /data/certs --domain-subdir --crt-name=fullchain --key-name=privkey --crt-ext=.pem --key-ext=.pem --watch'
        volumes:
            - ./ssl/cloudflare:/data
```

So it should place two files:
- `certs/domain.com/fullchain.pem`
- `certs/domain.com/privkey.pem`

Those two files are created fine, but I also have another folder / file created:
- `certs/private/letsencrypt.pem`

I read through the readme for this image, and I can't seem to figure out the purpose of that file.  The file has a `BEGIN EC PRIVATE KEY` header, is that just the EC version of the private key, the same as `certs/domain.com/fullchain.pem`?

The odd thing about that file is that I have XCA installed, which allows me to view the general details of a cert or key, and XCA says that file is corrupted and cannot open it, but it can open the other two files fine. But the `letsencrypt.pem` is not empty, it's about 4kb. XCA says it does not contain valid PKI data. Yet I also have my own private EC keys that open fine. This is the first time I've not been able to view a key.

Just basically trying to find out the purpose of `letsencrypt.pem`, and how it differs from the `privkey.pem` file I'm generating in the domain folder. I defined `key-name` as `--key-name=privkey`, so I'd assume the privkey file is the privkey.

And if there's a way to adjust that folder that key is saved to.

**Comment by ldez** [comment]
Hello,

`letsencrypt.key` is the private key of the Let's Encrypt account.

This is not a domain certificate, this is the key used to identify your LE account.

**Comment by Aetherinox** [comment]
Awesome. Appreciate this info. I was going crazy trying to Google where that file led to.

Thanks again.
