### ISSUE TITLE
Hook: Expand Environment Variables

### ISSUE THREAD

**Issue by dargmuesli** [ldez/traefik-certs-dumper#23]
Hey there,

first of all let me thank you for this great replacement of `dumpcerts.sh`!

I want to propose to change
https://github.com/ldez/traefik-certs-dumper/blob/a4b4be1fd448cfb0fbcd91d145b9b1a47c45201c/hook/hook.go#L19
to `errH := execute(os.ExpandEnv(command))` to be able to utilize environment variables within post-hooks.

**Comment by ldez** [comment]
Thanks for the proposal, the feature is in the v2.4.0

**Comment by dargmuesli** [comment]
Thank you, that was quick! :)
