### ISSUE TITLE
key <-> certificate ?

### ISSUE THREAD

**Issue by abate** [ldez/traefik-certs-dumper#3]
https://github.com/ldez/traefik-certs-dumper/blob/f7141a44aac93a71764a573f5d2a9633506f7dc9/dumper.go#L115

I can't stop wondering. should this line be `cert.Key` and not `cert.Certificate` ?

I've the impression that the two are inverted ...

**Comment by ldez** [comment]
Good catch!
Fixed in v1.4.1.
