### ISSUE TITLE
Don't remove certsSubDir and keysSubDir content if it's not part of acme.json

### ISSUE THREAD

**Issue by joseluisq** [ldez/traefik-certs-dumper#37]
My issue was that all my old files located on directories (`something/certs`, `something/private`) after `traefik-certs-dumper` execution were removed because `dumper.go` always removes `certsSubDir` and `keysSubDir` content completely.

**Command executed:**

```sh
~> traefik-certs-dumper file --source ./acme.json --dest ./something
```

**dumper.go:**
https://github.com/ldez/traefik-certs-dumper/blob/76880d271d361d29b7c7de03f6a4bff1dec20fd4/dumper/dumper.go#L107-L129

Please add a description about it in the `README` file too.

**Comment by ldez** [comment]
Hello,

those directories are clean **before** the execution.

The option to not remove this directory already exists and the documentation also:

```
 --clean              Clean destination folder before dumping content. (default true)
```
https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md#options-inherited-from-parent-commands

**Comment by joseluisq** [comment]
Hey!
Thanks for the clarification 👍
