### ISSUE TITLE
Support for running a shell script after successful dump?

### ISSUE THREAD

**Issue by poVoq** [ldez/traefik-certs-dumper#40]
Or something like that?

I need to move the dumped certs to my XMPP and IRC server, which involves copying them and changing the file permissions.

Anyone got an convenient option to (semi-)automate that?

Thanks :)

**Comment by ldez** [comment]
You can use `--post-hook` (only with watch mode and if the data source changes)

https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md

**Comment by poVoq** [comment]
Ahh, yeah that sounds exactly like what I had in mind *slaps forehead*

Ok, but now, how is that watch mode working? I need to set it up as a systemd service to run it in the background? Maybe I am overlooking something again, but it doesn't seem to be documented...

**Comment by ldez** [comment]
```
--watch              Enable watching changes.
```

https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md

In mode watch mode, the process never stop, like a server. So you can use a Docker image, systemd, ...
