### ISSUE TITLE
how install it?

### ISSUE THREAD

**Issue by stkac** [ldez/traefik-certs-dumper#5]
hi, someone knows how to install it, I'm new in the GoWorld..
thanks in advance,

**Comment by ldez** [comment]
* To get the binary just download the latest release for your OS/Arch from [the releases page](https://github.com/ldez/traefik-certs-dumper/releases/)
* Unzip the archive.

**Comment by stkac** [comment]
@ldez thanks!

One more thing, how to use it with docker? like:

`docker run -v "$PWD/certs:/export" ldez/traefik-certs-dumper:latest dump --source /export/certs/acme.json --dest /export/certs/dump/`

Thanks in advance,
