### ISSUE TITLE
Q: ca-chain.pem ?

### ISSUE THREAD

**Issue by Webunity** [ldez/traefik-certs-dumper#64]
Is it possible to also extract the CA-chain for a given domain?

**Comment by mozzhead164** [comment]
...is this possible? ...I need to use TLS certs for docker + mosquitto.

I'm using Traefik to generate certs for MQTTS but bypass the proxy (couldn't get TCP proxy working)

Connecting to MQTT.fx needs a rootCA attached. Any chance you could add this to make it easier?

**Comment by Webunity** [comment]
@mozzhead164 i ended up doing the following:
https://gist.github.com/Webunity/0534bfd666136fd9a936f09fcf8b0fcf

**Comment by Webunity** [comment]
btw, i run this in a cronjob:
`0 4 * * * /mnt/nas/docker/scripts/update_mqtt_cert.sh >/dev/null 2>&1`
