### ISSUE TITLE
Not dumping Traefik v2 Certificates

### ISSUE THREAD

**Issue by mmance** [ldez/traefik-certs-dumper#70]
sudo traefik-certs-dumper file --source ../traefik/data/acme.json --dest . --domain-subdir --crt-name=fullchain --key-name=privkey

Does this not work with traefik v2 acme.json yet?

**Comment by ldez** [comment]
https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md

> --version string   Traefik version. If empty use v1. Possible values: 'v2'.
