### ISSUE TITLE
[request] allow specifying acme.json alternative filename or multiple

### ISSUE THREAD

**Issue by tomwiggers** [ldez/traefik-certs-dumper#71]
Hi,

In my Traefik setup I manage a variety of domains and I keep domains from different "organizations" in different JSON files. Currently, I do not see a way to make this work with the traefik-certs-dumper.

Am I overlooking something or is this not possible at this time? If the latter, could this be made possible?

**Comment by ldez** [comment]
Hello,

you can use a lot of options to customize the dumper (by example `source`)

- https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md
- https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md#options
- https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper_file.md#options-inherited-from-parent-commands

https://github.com/ldez/traefik-certs-dumper#examples

**Comment by tomwiggers** [comment]
Thank you!
