### ISSUE TITLE
Unable to use arguments containing spaces in --post-hook

### ISSUE THREAD

**Issue by hermlon** [ldez/traefik-certs-dumper#80]
https://github.com/ldez/traefik-certs-dumper/blob/0ad349de7ad14bf98a592be04ffb755e32744e77/hook/hook.go#L31-L32
Because the `string.Fields` function splits at every single space it is impossible to execute a command with an argument containing spaces. For example `--post-hook "mkdir t\ est"` will create two direcories `t\` and `est` instead of `t est` because both are treated as separate arguments.
Would it be a bad practice to just always execute `/bin/sh` and pass the whole `command` as a single argument?

**Comment by ldez** [comment]
Hello,

I recommend to use a script instead of a simple command line.
