### ISSUE TITLE
Feature request: ability to watch for specific certificates

### ISSUE THREAD

**Issue by J7mbo** [ldez/traefik-certs-dumper#86]
Traefik updates `acme.json` as it goes along. Given several subdomains for example, I might have to wait several times for acme.json to update to contain the specific letsencrypt key I'm waiting for. Only when this key exists do I want to dump and copy the files to the service requiring those for that specific subdomain certificate. There are a few use-cases I can list where a wildcard cert wouldn't work in this instance.

It would be great to come up with some sort of configuration option that would allow users to say "when mysubdomain.domain.com appears, give me that certificate and key for it in this place".

As of right now I'll have to write a not-so-nice script to handle this. It'd be great if `traefik-certs-dumper` could handle it.

Alongside this would be the useful ability to extract specific certs / keys and place them in something much nicer than `dump/`, say the cert and key file for this domain in a specific directory, but maybe you won't like that. It'd be a nice to have anyway!

**Comment by ldez** [comment]
Hello,

you can already change the output folder: https://github.com/ldez/traefik-certs-dumper#examples

**Comment by ldez** [comment]
For the hook, I want to keep it simple, so I think that is simple to create a simple script to handle only a domain.

**Comment by J7mbo** [comment]
Fair enough. Also @ldez just wanted to say - thanks so much for your work and responding to traefik questions etc on the forums - your answers have been super helpful for me and I'm sure others too. :)
