### ISSUE TITLE
Feature Request: Would it be possible to dump certs for certain domains?

### ISSUE THREAD

**Issue by tonymmm1** [ldez/traefik-certs-dumper#92]
Having some sort of flag such as traefik-certs-dumper --domain www.site.com for dumping specific domains.

**Comment by ldez** [comment]
Hello,

could you explain why do you want this?

**Comment by tonymmm1** [comment]
I would like to be able to use the dumper container so that I can dump traefik certs for mailcow specifically so that I can use included watch feature and only send it the specific domain certs.

**Comment by tonymmm1** [comment]
This is what I used with Traefik v1.7 but using your container would be much more convenient than relying on inotify and additional script. https://github.com/jovobe/mailcow-traefik-acme-adapter/

**Comment by ldez** [comment]
I think that can you the `--post-hook` flag.

https://github.com/ldez/traefik-certs-dumper/blob/master/docs/traefik-certs-dumper.md
